### ISSUE TITLE
themes: todo/wip list

### ISSUE THREAD

**Issue by icxes** [R-a-dio/valkyrie#149]
This is for me in particular so I don't forget, I'll update this as I notice stuff and fix them eventually

css, exact:
- [x] #current-song-progress: background-color to var(--radio-secondary-1);
- [x] .notification: background-color to var(--radio-secondary-1) !important;
- [x] .dj-image-name-64: add text-wrap: nowrap;

css, general:
- [x] fix some inconsistent gaps between elements (front page stream container buttons, queue/lp page elements...)
  - related: #135
- [x] vertically align items in front page stream container
- [x] fix #options-button-dropdown button colors
- [x] better buttons for song info dropdowns (the button idea is ok but could look a bit better) 
  - related: #133

misc:
- [x] there is no footer 
  - related: #153
- [x] staff page is awful, maybe just try to make it look as close to the old one as possible

not blocking anything but should fix anyway:
- [x] faves page needs some specific styling that's different from search page
- [x] less saturated border bloom when activating text fields
- [x] submit page accept/decline cells both stretch to whatever length the taller one has
- [x] pending page UI is kinda bad
- [x] database page is also kinda bad

**Comment by icxes** [comment]
Can't do much about the pending page right now since I can't upload songs (#156 ?)

**Comment by icxes** [comment]
Can't think of much on the theme side that absolutely has to be done before 1.0 anymore so closing this
